package presentation;
//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

import business.Restaurant;

public class MainFrame {
	private JButton adminButton;
	private JButton waiterButton;
	private JButton chefButton;


	public MainFrame(final Restaurant restaurant) {
		
		//construct components
		adminButton = new JButton ("Administrator");
		waiterButton = new JButton ("Waiter");
		chefButton = new JButton ("Chef");

		JFrame frame = new JFrame("Restaurant");
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setSize(new Dimension(367, 297));
		frame.setLocationRelativeTo(null);
		
		JPanel p=new JPanel();
		p.setLayout (null);
		
		//set component bounds (only needed by Absolute Positioning)
		adminButton.setBounds (105, 35, 140, 55);
		waiterButton.setBounds (105, 105, 140, 55);
		chefButton.setBounds (105, 175, 140, 55);

		//add components
		p.add(adminButton);
		p.add(waiterButton);
		p.add(chefButton);
		
		frame.setContentPane(p);
		frame.setVisible(true);
		
	}

	public JButton getAdmin(){
		return this.adminButton;
	}
	
	public JButton getWaiter(){
		return this.waiterButton;

	}
	
	public JButton getChef(){
		return this.chefButton;
	}
	
	void addListener(ActionListener listen){
		adminButton.addActionListener(listen);
		waiterButton.addActionListener(listen);
		chefButton.addActionListener(listen);
	}
}


